//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seren.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizations_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Seren.Resources.Strings.Localizations_ru", typeof(Localizations_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PanicSign {
            get {
                return ResourceManager.GetString("PanicSign", resourceCulture);
            }
        }
        
        internal static string Meditation {
            get {
                return ResourceManager.GetString("Meditation", resourceCulture);
            }
        }
        
        internal static string MeditationDescription {
            get {
                return ResourceManager.GetString("MeditationDescription", resourceCulture);
            }
        }
        
        internal static string HelpYourself {
            get {
                return ResourceManager.GetString("HelpYourself", resourceCulture);
            }
        }
        
        internal static string HelpYourselfDescription {
            get {
                return ResourceManager.GetString("HelpYourselfDescription", resourceCulture);
            }
        }
        
        internal static string Breath {
            get {
                return ResourceManager.GetString("Breath", resourceCulture);
            }
        }
        
        internal static string BreathDescription {
            get {
                return ResourceManager.GetString("BreathDescription", resourceCulture);
            }
        }
        
        internal static string DoYouHavePanic {
            get {
                return ResourceManager.GetString("DoYouHavePanic", resourceCulture);
            }
        }
        
        internal static string YouHavePanic {
            get {
                return ResourceManager.GetString("YouHavePanic", resourceCulture);
            }
        }
        
        internal static string HowStrongIsAttack {
            get {
                return ResourceManager.GetString("HowStrongIsAttack", resourceCulture);
            }
        }
        
        internal static string AttackStrongness1 {
            get {
                return ResourceManager.GetString("AttackStrongness1", resourceCulture);
            }
        }
        
        internal static string AttackStrongness3 {
            get {
                return ResourceManager.GetString("AttackStrongness3", resourceCulture);
            }
        }
        
        internal static string AttackStrongness5 {
            get {
                return ResourceManager.GetString("AttackStrongness5", resourceCulture);
            }
        }
        
        internal static string AttackStrongness4 {
            get {
                return ResourceManager.GetString("AttackStrongness4", resourceCulture);
            }
        }
        
        internal static string AttackStrongness2 {
            get {
                return ResourceManager.GetString("AttackStrongness2", resourceCulture);
            }
        }
        
        internal static string Panic {
            get {
                return ResourceManager.GetString("Panic", resourceCulture);
            }
        }
        
        internal static string Exhale {
            get {
                return ResourceManager.GetString("Exhale", resourceCulture);
            }
        }
        
        internal static string Inhale {
            get {
                return ResourceManager.GetString("Inhale", resourceCulture);
            }
        }
        
        internal static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_AdrenalineResponse {
            get {
                return ResourceManager.GetString("PanicQuestionary.AdrenalineResponse", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_EveryoneThinksImCrazy {
            get {
                return ResourceManager.GetString("PanicQuestionary.EveryoneThinksImCrazy", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_EveryoneThinksImSick {
            get {
                return ResourceManager.GetString("PanicQuestionary.EveryoneThinksImSick", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_EveryoneThinksImWeak {
            get {
                return ResourceManager.GetString("PanicQuestionary.EveryoneThinksImWeak", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_FearCanKillMe {
            get {
                return ResourceManager.GetString("PanicQuestionary.FearCanKillMe", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_FearWillPass {
            get {
                return ResourceManager.GetString("PanicQuestionary.FearWillPass", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_ICanBeatPanicAttack {
            get {
                return ResourceManager.GetString("PanicQuestionary.ICanBeatPanicAttack", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_ICanBecomeAggressive {
            get {
                return ResourceManager.GetString("PanicQuestionary.ICanBecomeAggressive", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_ICanDie {
            get {
                return ResourceManager.GetString("PanicQuestionary.ICanDie", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_ICanSuffocate {
            get {
                return ResourceManager.GetString("PanicQuestionary.ICanSuffocate", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_MyBrainIsHealthy {
            get {
                return ResourceManager.GetString("PanicQuestionary.MyBrainIsHealthy", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_ImParalyzed {
            get {
                return ResourceManager.GetString("PanicQuestionary.ImParalyzed", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_IWillFaint {
            get {
                return ResourceManager.GetString("PanicQuestionary.IWillFaint", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_IWillGoCrazy {
            get {
                return ResourceManager.GetString("PanicQuestionary.IWillGoCrazy", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_IWillHaveHeartAttack {
            get {
                return ResourceManager.GetString("PanicQuestionary.IWillHaveHeartAttack", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_IWillHaveStroke {
            get {
                return ResourceManager.GetString("PanicQuestionary.IWillHaveStroke", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_IWillLoseTouchWithReality {
            get {
                return ResourceManager.GetString("PanicQuestionary.IWillLoseTouchWithReality", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_MyHeartIsHealthy {
            get {
                return ResourceManager.GetString("PanicQuestionary.MyHeartIsHealthy", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_PanicAttackIsSafe {
            get {
                return ResourceManager.GetString("PanicQuestionary.PanicAttackIsSafe", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_PanicAttackWillKillMe {
            get {
                return ResourceManager.GetString("PanicQuestionary.PanicAttackWillKillMe", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_PanicAttackWillLastForever {
            get {
                return ResourceManager.GetString("PanicQuestionary.PanicAttackWillLastForever", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_ShouldICallAmbulance {
            get {
                return ResourceManager.GetString("PanicQuestionary.ShouldICallAmbulance", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_ShouldICheckPulse {
            get {
                return ResourceManager.GetString("PanicQuestionary.ShouldICheckPulse", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_ShouldITryToDistract {
            get {
                return ResourceManager.GetString("PanicQuestionary.ShouldITryToDistract", resourceCulture);
            }
        }
        
        internal static string PanicQuestionary_WhatIFeelIsNormal {
            get {
                return ResourceManager.GetString("PanicQuestionary.WhatIFeelIsNormal", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
