//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seren.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizations_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Seren.Resources.Strings.Localizations_ru", typeof(Localizations_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Panic {
            get {
                return ResourceManager.GetString("Panic", resourceCulture);
            }
        }
        
        internal static string Meditation {
            get {
                return ResourceManager.GetString("Meditation", resourceCulture);
            }
        }
        
        internal static string MeditationDescription {
            get {
                return ResourceManager.GetString("MeditationDescription", resourceCulture);
            }
        }
        
        internal static string HelpYourself {
            get {
                return ResourceManager.GetString("HelpYourself", resourceCulture);
            }
        }
        
        internal static string HelpYourselfDescription {
            get {
                return ResourceManager.GetString("HelpYourselfDescription", resourceCulture);
            }
        }
        
        internal static string Breath {
            get {
                return ResourceManager.GetString("Breath", resourceCulture);
            }
        }
        
        internal static string BreathDescription {
            get {
                return ResourceManager.GetString("BreathDescription", resourceCulture);
            }
        }
        
        internal static string DoYouHavePanic {
            get {
                return ResourceManager.GetString("DoYouHavePanic", resourceCulture);
            }
        }
    }
}
